#@yaml/text-templated-strings
#@ load("@ytt:data", "data")
#@ load("_traefik.star", "traefik_labels")
---
#@ if data.values.php.enabled:
version: '2.2'

services:
  nginx:
    image: #@ data.values.php.nginx.image
    restart: always
    #@ if not hasattr(data.values.php.nginx, "configFiles"):
    entrypoint: sh
    command:
      - -c
      - |
        cat << EOF | tee /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"
        server {
          listen 80;

          root  (@= data.values.php.nginx.document_root @);
          index index.html index.htm index.php;

          location / {
            try_files \$uri \$uri/ /index.php?\$query_string;
          }

          location ~ \.php {
            fastcgi_pass    php:9000;
            fastcgi_param   SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
            include         fastcgi_params;
            internal;
          }
        }
        EOF
    #@ end
    labels: #@ traefik_labels("nginx", data.values.php)
    volumes_from:
      - php

  php:
    image: #@ data.values.php.image
    restart: always
    working_dir: (@= data.values.php.working_dir @)
    #@ if hasattr(data.values.php, "environment"):
    environment: #@ data.values.php.environment
    #@ end
    volumes:
      - (@= data.values.php.mount @):(@= data.values.php.working_dir @)
      - (@= data.values.hosts_file @):/etc/hosts
#@ end
